# Generated by Django 5.1.6 on 2025-02-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='played_at',
            field=models.DateTimeField(),
        ),
    ]
