# Generated by Django 5.1.6 on 2025-02-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_match_played_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('draw', 'Draw'), ('not_played', 'Not Played')], default='not_played', max_length=20),
        ),
    ]
