# Generated by Django 5.1.6 on 2025-02-23 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_match_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticpantStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_matches_played', models.IntegerField(default=0)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_losses', models.IntegerField(default=0)),
                ('total_draws', models.IntegerField(default=0)),
                ('highest_elo_rating', models.IntegerField(default=1200)),
                ('particpant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.participant')),
            ],
        ),
    ]
