# Generated by Django 5.1.6 on 2025-02-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_particpantstats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParticpantStats',
            new_name='ParticipantStats',
        ),
    ]
