# Generated by Django 5.1.6 on 2025-02-23 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_participantstats_particpant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantstats',
            old_name='total_draws',
            new_name='draws',
        ),
        migrations.RenameField(
            model_name='participantstats',
            old_name='total_losses',
            new_name='losses',
        ),
        migrations.RenameField(
            model_name='participantstats',
            old_name='total_matches_played',
            new_name='matches_played',
        ),
        migrations.RenameField(
            model_name='participantstats',
            old_name='highest_elo_rating',
            new_name='peak_elo',
        ),
        migrations.RenameField(
            model_name='participantstats',
            old_name='total_wins',
            new_name='wins',
        ),
    ]
