# Generated by Django 5.1.6 on 2025-02-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_total_draws_participantstats_draws_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='participant1_elo_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='participant2_elo_change',
            field=models.IntegerField(default=0),
        ),
    ]
